[module]
name = "buildSystem"
visibility = "package"
root = "mod.qn"
owner = "qtlang/compiler/buildSystem"
role = "build-system"

[dependencies]
modules = ["backend", "buildSystem.stage", "frontend", "hir", "host", "typeSystem"]
